package com.gstfkz.parismetrogame.ui.screen
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Close
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.gstfkz.parismetrogame.data.model.*
@Composable fun GameScreen(departureStation:MetroStation,arrivalStation:MetroStation,segments:List<UserSegment>,availableLines:List<MetroLine>,stationsForLine:(MetroLine)->List<MetroStation>,txt:UiText,onSegmentChange:(Int,UserSegment)->Unit,onAddRow:()->Unit,onRemoveRow:(Int)->Unit,onVerify:()->Unit){Column(Modifier.fillMaxSize().safeDrawingPadding().padding(16.dp)){AutoFitRouteTitle(departureStation.name,arrivalStation.name);HorizontalDivider(Modifier.padding(vertical=16.dp));LazyColumn(Modifier.weight(1f)){items(segments.size){i->SegmentRow(segments[i],availableLines,stationsForLine,txt,{onSegmentChange(i,it)},if(segments.size>1){{onRemoveRow(i)}}else null);HorizontalDivider(Modifier.padding(vertical=10.dp))}};if(segments.lastOrNull()?.isComplete==true)Row(Modifier.fillMaxWidth().padding(bottom=8.dp),horizontalArrangement=Arrangement.SpaceBetween){FilledIconButton(onAddRow){Icon(Icons.Default.Add,txt.t("Add","Ajouter"))};Button(onVerify){Text(txt.t("Check","Vérifier"))}}}}
@Composable private fun AutoFitRouteTitle(a:String,b:String){val n=a.length+b.length;val style=when{n>50->MaterialTheme.typography.bodyMedium;n>38->MaterialTheme.typography.bodyLarge;n>28->MaterialTheme.typography.titleMedium;else->MaterialTheme.typography.headlineSmall};Text("$a  →  $b",style=style,maxLines=1,overflow=TextOverflow.Clip)}
@Composable private fun SegmentRow(s:UserSegment,lines:List<MetroLine>,stations:(MetroLine)->List<MetroStation>,txt:UiText,change:(UserSegment)->Unit,remove:(()->Unit)?){Column(Modifier.fillMaxWidth()){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){LineDropdown(Modifier.weight(1f),txt.t("Line","Ligne"),lines,s.line){change(UserSegment(line=it))};remove?.let{OutlinedIconButton(it){Icon(Icons.Default.Close,txt.t("Remove","Supprimer"))}}};Spacer(Modifier.height(8.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){val opts=s.line?.let(stations).orEmpty();Dropdown(Modifier.weight(1f),txt.t("From","Départ"),opts,{it.name},s.departureStation,s.line!=null){change(s.copy(departureStation=it))};Text("→",Modifier.padding(top=18.dp));Dropdown(Modifier.weight(1f),txt.t("To","Arrivée"),opts,{it.name},s.arrivalStation,s.line!=null){change(s.copy(arrivalStation=it))}}}}
@OptIn(ExperimentalMaterial3Api::class)@Composable private fun LineDropdown(modifier:Modifier,label:String,options:List<MetroLine>,selected:MetroLine?,pick:(MetroLine)->Unit){var open by remember{mutableStateOf(false)};ExposedDropdownMenuBox(open,{open=it},modifier){OutlinedTextField(selected?.displayName.orEmpty(),{},Modifier.menuAnchor().fillMaxWidth(),readOnly=true,label={Text(label)},singleLine=true,trailingIcon={ExposedDropdownMenuDefaults.TrailingIcon(open)});DropdownMenu(open,{open=false},Modifier.exposedDropdownSize()){options.forEachIndexed{i,o->DropdownMenuItem({Row(verticalAlignment=Alignment.CenterVertically){LineBadge(o);Spacer(Modifier.width(10.dp));if(o.mode==TransportMode.WALK)Text("Walk")}}, {pick(o);open=false});if(i<options.lastIndex)HorizontalDivider()}}}}
@OptIn(ExperimentalMaterial3Api::class)@Composable private fun<T>Dropdown(modifier:Modifier,label:String,options:List<T>,name:(T)->String,selected:T?,enabled:Boolean,pick:(T)->Unit){var open by remember{mutableStateOf(false)};ExposedDropdownMenuBox(open&&enabled,{if(enabled)open=it},modifier){OutlinedTextField(selected?.let(name).orEmpty(),{},Modifier.menuAnchor().fillMaxWidth(),enabled=enabled,readOnly=true,label={Text(label)},singleLine=true,trailingIcon={ExposedDropdownMenuDefaults.TrailingIcon(open&&enabled)});DropdownMenu(open&&enabled,{open=false},Modifier.exposedDropdownSize()){options.forEachIndexed{i,o->DropdownMenuItem({Text(name(o),maxLines=1,overflow=TextOverflow.Ellipsis)},{pick(o);open=false});if(i<options.lastIndex)HorizontalDivider()}}}}
